[package]
name = "darkpool-indexer"
version = "0.1.0"
edition = "2024"

[dependencies]
# === Renegade === #
renegade-constants = { workspace = true }
renegade-common = { workspace = true }
renegade-crypto = { workspace = true }
ark-mpc = { git = "https://github.com/renegade-fi/ark-mpc" } # We import this here so that its default features are set 

# === Runtime === #
tokio = { version = "1.10", features = ["full"] }
clap = { version = "4.5.3", features = ["derive", "env"] }

# === DB === #
diesel = { workspace = true, features = ["postgres", "numeric", "uuid"] }
diesel-async = { workspace = true, features = ["postgres", "bb8"] }
bb8 = { workspace = true }
native-tls = { workspace = true }
postgres-native-tls = { workspace = true }
tokio-postgres = { workspace = true }
bigdecimal = "0.4"
uuid = { version = "1.17.0", features = ["v4", "serde"] }

# === AWS === #
aws-config = { version = "1.1.4", features = ["behavior-version-latest"] }
aws-sdk-sqs = "1.50.0"

# === API === #
serde = "1.0"
serde_json = "1.0"

# === Crypto === #
tiny-keccak = { version = "2.0", features = ["keccak", "sha3"] }

# === Misc === #
thiserror = { workspace = true }
tracing = { workspace = true }
itertools = "0.10"

[dev-dependencies]
rand = "0.8"
