
###################
### Auth Server ###
###################

[services.arbitrum-sepolia-auth-server]
[services.arbitrum-sepolia-auth-server.build]
dockerfile = "auth/Dockerfile"
ecr_repo = "auth-server-arbitrum-sepolia"
cargo_features = "arbitrum"

[services.arbitrum-sepolia-auth-server.deploy]
environment = "arbitrum-sepolia"
resource = "auth-server"

[services.base-sepolia-auth-server]
[services.base-sepolia-auth-server.build]
dockerfile = "auth/Dockerfile"
ecr_repo = "auth-server-base-sepolia"
cargo_features = "base"

[services.base-sepolia-auth-server.deploy]
environment = "base-sepolia"
resource = "auth-server"

[services.arbitrum-one-auth-server]
[services.arbitrum-one-auth-server.build]
dockerfile = "auth/Dockerfile"
ecr_repo = "auth-server-arbitrum-one"
cargo_features = "arbitrum"

[services.arbitrum-one-auth-server.deploy]
environment = "arbitrum-one"
resource = "auth-server"

[services.base-mainnet-auth-server]
[services.base-mainnet-auth-server.build]
dockerfile = "auth/Dockerfile"
ecr_repo = "auth-server-base-mainnet"
cargo_features = "base"

[services.base-mainnet-auth-server.deploy]
environment = "base-mainnet"
resource = "auth-server"

#####################
### Funds Manager ###
#####################

[services.testnet-funds-manager]
[services.testnet-funds-manager.build]
dockerfile = "funds-manager/Dockerfile"
ecr_repo = "funds-manager-testnet"

[services.testnet-funds-manager.deploy]
environment = "testnet"
resource = "funds-manager"

[services.mainnet-funds-manager]
[services.mainnet-funds-manager.build]
dockerfile = "funds-manager/Dockerfile"
ecr_repo = "funds-manager-mainnet"

[services.mainnet-funds-manager.deploy]
environment = "mainnet"
resource = "funds-manager"
