on: push

name: Clippy Check

env:
  CLIPPY_ARGS: >
    --tests
    --benches
    --
    --no-deps
    -D warnings
    -D unsafe_code
    -D missing_docs
    -D clippy::missing_docs_in_private_items
    -D clippy::needless_pass_by_value
    -D clippy::needless_pass_by_ref_mut
    -D clippy::unused_async

jobs:
  clippy-workspace:
    name: Clippy (workspace)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: Swatinem/rust-cache@v2
      - run: rustup component add clippy
      - name: Run clippy on workspace
        run: cargo clippy --workspace --exclude auth-server ${{ env.CLIPPY_ARGS }}

  clippy-auth-server:
    name: Clippy (auth-server/${{ matrix.features }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features: ["arbitrum", "base"]
    steps:
      - uses: actions/checkout@v4
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.features }}
      - run: rustup component add clippy
      - name: Run clippy on auth-server
        run: cargo clippy -p auth-server --no-default-features --features ${{ matrix.features }} ${{ env.CLIPPY_ARGS }}
