on: push

name: Cargo Test

env:
  CARGO_TERM_COLOR: always

jobs:
  test-workspace:
    name: Test (workspace)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain from file
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2025-11-25
          components: clippy

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: Swatinem/rust-cache@v2
      - name: Build workspace
        run: cargo build --workspace --exclude auth-server
      - name: Test workspace
        run: cargo test --workspace --exclude auth-server --verbose -- --skip integration

  test-auth-server:
    name: Test (auth-server/${{ matrix.features }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features: ["arbitrum", "base"]
    steps:
      - uses: actions/checkout@v4
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.features }}
      - name: Build auth-server
        run: cargo build --package auth-server --features ${{ matrix.features }}
      - name: Test auth-server
        run: cargo test --package auth-server --features ${{ matrix.features }} --verbose -- --skip integration
